sample_rate: 24000
batch_size: 2

featex: # feature extraction module; components receive the output of torchaudio.load as input.
  hubert:
    cls: spkanon_models.barkvc.hubert.Hubert
    hubert_tokenizer_path: checkpoints/bark/tokenizer.pth
    hubert_path: checkpoints/bark/text_2.pth

featproc: # feature processing module
  barkvc:
    cls: spkanon_models.barkvc.converter.BarkVC
    target_feats: ${target_feats}
    target_min_dur: 3
    target_max_dur: 10
    exp_folder: ${exp_folder}
    input:
      feats: feats
      n_feats: n_feats
      source: source
      target: target
  output: # what is passed to the next module
    featproc:
      - encodec
      - target
      - n_feats
    featex: [] # non-processed features, from the featex config group

synthesis: # speech synthesis; receives featfusion's output as input
  cls: spkanon_models.barkvc.decoder.EncodecDecoder
  input:
    encodec: encodec
    n_feats: n_feats
