name: "Multi-speaker FastPitch + corresponding HiFi-GAN"
sample_rate: 44100

featex: # feature extraction module; components receive the output of torchaudio.load as input.
  whisper:
    cls: spkanon_eval.featex.asr.whisper_wrapper.Whisper
    train: false
    size: small # can be: tiny, base, small, medium, large
    output: text # can be text or encoding
    max_chars_div: 800  # used to prevent hallucinations

featproc: # feature processing module
  fast_pitch:
    cls: spkanon_models.whisper_fastpitch.fast_pitch.FastPitch
    init: tts_en_fastpitch_multispeaker
    input:
      text: whisper
      source: source
      source_is_male: source_is_male
    n_targets: 20
  output: # what is passed to the next module
    featproc:
      - spectrogram
      - lengths
      - target
    featex: [] # non-processed features, from the featex config group

synthesis: # speech synthesis; receives featfusion's output as input
  cls: spkanon_models.whisper_fastpitch.hifigan.HifiGan
  init: tts_en_hifitts_hifigan_ft_fastpitch
  input:
    spectrogram: spectrogram
    lengths: lengths
