name: "Multi-speaker FastPitch + corresponding HiFi-GAN"

sample_rate: 16000 # SR of the input audio

featex: # feature extraction module; components receive the output of torchaudio.load as input.
  whisper:
    cls: src.featex.asr.whisper.Whisper
    train: false
    size: small # can be: tiny, base, small, medium, large
    output: text # can be text or encoding
    batch_size: 4

featproc: # feature processing module
  fast_pitch:
    cls: src.featproc.fast_pitch.FastPitch
    init: tts_en_fastpitch_multispeaker
    input:
      text: whisper
      source: source
      target: target
    n_targets: 20
  output: # what is passed to the next module
    featproc:
      - spectrogram
      - target
    featex: [] # non-processed features, from the featex config group

synthesis: # speech synthesis; receives featfusion's output as input
  cls: src.synthesis.hifigan.HifiGan
  init: tts_en_hifitts_hifigan_ft_fastpitch
  sample_rate: 44100
  input:
    spectrogram: spectrogram
